server:
  domain: user
  version: 1.0
  jwtSecret: chuyu
  grpcAddress: "127.0.0.1:10001"

mysql:
  drivername: mysql
  host: 127.0.0.1
  port: 13306
  database: grpc_todolist
  username: root
  password: 123456
  charset: utf8mb4

etcd: 
  address: [127.0.0.1:12379, 127.0.0.1:22379, 127.0.0.1:32379]

redis:
  address: 127.0.0.1:16379
  password: